version: '3.4'

networks:
  webapinetwork:

services:
  webapi4:
    image: ${DOCKER_REGISTRY-}webapi4
    container_name: webapi-application
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: WebApi4/Dockerfile
    depends_on: [ aowdb ]
    networks:
    - webapinetwork
    environment:
    - DB_HOST=aowdb
    #- DB_Name=aownew
    #- DB_SA_Password=Password#1

  aowdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - 8002:1433 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Password#1
    networks:
      - webapinetwork

  aowmysqldb:
    image: mysql:8.0.31-debian
    container_name: mysqldb8031
    ports:
      - 8004:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password#1
    networks:
      - webapinetwork

  webapi3:
    image: ${DOCKER_REGISTRY-}webapi3
    build:
      context: .
      dockerfile: WebApi3/Dockerfile
    ports:
      - 5004:80
    depends_on: [ aowmysqldb ]
    networks:
      - webapinetwork

