version: '3.4'

networks:
  webapinetwork:

services:
  webapi4:
    image: ${DOCKER_REGISTRY-}webapi4
    container_name: webapi-application
    #ports:
    #  - 5000:80
    build:
      context: .
      dockerfile: WebApi4/Dockerfile
    depends_on: [ aowdb ]
    networks:
    - webapinetwork
    environment:
    - DB_HOST=aowdb
    #- DB_Name=aownew
    #- DB_SA_Password=Password#1

  db:    
    image: mysql:8.0.31-debian
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password#1
      MYSQL_DATABASE: phyadmindb
      MYSQL_USER: myadminuser
      MYSQL_PASSWORD: Password#1
    networks:
      - phpmyadmin-network

  aowdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - 8002:1433 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Password#1
    networks:
      - webapinetwork

  aowmysqldb:
    image: mysql:8.0.31-debian
    container_name: mysqldb8031
    ports:
      - 8004:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password#1
    networks:
      - webapinetwork

  db:    
    image: mysql:8.0.31-debian
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password#1
      MYSQL_DATABASE: phyadmindb
      MYSQL_USER: myadminuser
      MYSQL_PASSWORD: Password#1
    networks:
      - phpmyadmin-network
 
  phpmyadmin:   
    depends_on: - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Password#1
	MYSQL_USER: myadminuser
      MYSQL_PASSWORD: Password#1
    networks:
      - phpmyadmin-network

  webapi3:
    image: ${DOCKER_REGISTRY-}webapi3
    build:
      context: .
      dockerfile: WebApi3/Dockerfile
    #ports:
    #  - 5004:80
    depends_on: [ aowmysqldb ]
    networks:
      - webapinetwork
    environment:
    - DB_HOST=aowmysqldb
    #- DB_Name=aownew
    #- DB_SA_Password=Password#1


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 5105:80
    networks:
      - webapinetwork

